Support type parameters in Exposed property mapping with some reflection-related code added and reorganized
Major changes:

1. Support type parameters and type inference in Exposed property mapping

   support for star projects require further refinement.

   1. parameterized property return type inference
   2. subclass type parameter inference
      1. GADT type parameter inference for sealed subclasses
2. Support object in Exposed property mapping (mainly for case objects of sealed classes)
3. Extract and add needed reflection-related code in the `:reflect` subproject, mainly related to type unification and substitution, and add unit tests for them

The problem of generating mappers for sealed classes with type parameters is similar to what occurs in kotlinx.serialization, so its source especially `serializer(type: KType)` and how it deals with sealed classes are studied. Interestingly, star projections are not supported as well.

For the code with kotlinx.serialization 1.5.1:

```kotlin
@Serializable
sealed class C<T> {
    @Serializable
    class Sub<T>(val a: T) : C<List<T>>()
}

fun main() {
    val c: C<List<Int>> = C.Sub(1)
    println(Json.encodeToString(c))
}
```

The error message is shown as follows:
> kotlinx.serialization.SerializationException: Class 'Int' is not registered for polymorphic serialization in the scope of 'Any'.
To be registered automatically, class 'Int' has to be '@Serializable', and the base class 'Any' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'Int' explicitly in a corresponding SerializersModule.

Some miscellaneous changes:

1. Add an interface `BidirectionalConversion`
1. In ClassPropertyMapping.kt while debugging our internal project:
   1. Refactor some code
   1. Fix numerous bugs
   1. Add numerous custom exception messages
   1. Add TODOs for further improvement
1. Vert.x `WebClient.close` is reverted (see https://github.com/vert-x3/vertx-web/commit/8dda3dec91648eddae01455b8a94cc1c0e25c864)
1. Add `DebugUpdateBuilderWrapper`