Increase the Gradle JVM heap space because it's not enough for the CI
The messages from the CI workflow:

```text
The Daemon will expire after the build after running out of JVM heap space.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '341.5 MiB' and the configured max metaspace is '384 MiB'.
For more information on how to set these values, please refer to https://docs.gradle.org/8.10.2/userguide/build_environment.html#sec:configuring_jvm_memory in the Gradle documentation.
To disable this warning, set 'org.gradle.daemon.performance.disable-logging=true'.
Daemon will be stopped at the end of the build after running out of JVM heap space
```

```text
> Task :kotlin-common-core:linkDebugTestIosSimulatorArm64
w: Failed to build cache: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```